import 'dart:ui';
import 'package:flutter/material.dart';

String _appTheme = "";

class ThemeHelper {
  Map<String, PrimaryTheme> _supportedThemes = {
    "primary": PrimaryTheme(),
    "secondary": SecondaryTheme(),
  };

  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  PrimaryTheme _getDefaultTheme() {
    //return default strings if locale is not set
    if (_appTheme.isEmpty) {
      return PrimaryTheme();
    }

    //throw exception to notify given local is not found or not generated by the generator
    if (!_supportedThemes.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this locale in JSON file Try running flutter pub run build_runner");
    }

    //return locale from map
    return _supportedThemes[_appTheme] ?? PrimaryTheme();
  }

  PrimaryTheme theme() => _getDefaultTheme();
}

class PrimaryTheme {
  Color get blueA700 => fromHex("#FF02843c");
  Color get gray80049 => fromHex("#493c3c43");
  Color get gray50 => fromHex("#f9fbff");
  Color get gray30099 => fromHex("#99e4e4e4");
  Color get black90087 => fromHex("#87000000");
  Color get black90001 => fromHex("#000919");
  Color get black900 => fromHex("#090b0d");
  Color get blueGray800 => fromHex("#37334d");
  Color get blueGray900 => fromHex("#262b35");
  Color get black90003 => fromHex("#000000");
  Color get black90002 => fromHex("#000000");
  Color get deepOrangeA400 => fromHex("#ff4b00");
  Color get gray70011 => fromHex("#11555555");
  Color get blueGray200 => fromHex("#bac1ce");
  Color get gray400 => fromHex("#c4c4c4");
  Color get blueGray100 => fromHex("#d6dae2");
  Color get blueGray400 => fromHex("#74839d");
  Color get blue700 => fromHex("#FF079e4a");
  Color get blueGray300 => fromHex("#9ea8ba");
  Color get blueGray600 => fromHex("#5f6c86");
  Color get mainTheme => fromHex("#ff079E4A");
  Color get gray80099 => fromHex("#993c3c43");
  Color get black9000c => fromHex("#0c000000");
  Color get gray300 => fromHex("#e3e4e5");
  Color get blue50 => fromHex("#e0ebff");
  Color get gray100 => fromHex("#f3f4f5");
  Color get black90075 => fromHex("#75000000");
  Color get black90033 => fromHex("#33000000");
  Color get blueGray40001 => fromHex("#888888");
  Color get whiteA700 => fromHex("#ffffff");
}

class SecondaryTheme extends PrimaryTheme {
  Color get blueA700 => fromHex("#FF02843c");
  Color get gray80049 => fromHex("#493c3c43");
  Color get gray50 => fromHex("#f9fbff");
  Color get gray30099 => fromHex("#99e4e4e4");
  Color get black90087 => fromHex("#87000000");
  Color get black90001 => fromHex("#000919");
  Color get black900 => fromHex("#090b0d");
  Color get blueGray800 => fromHex("#37334d");
  Color get blueGray900 => fromHex("#262b35");
  Color get black90003 => fromHex("#000000");
  Color get black90002 => fromHex("#000000");
  Color get deepOrangeA400 => fromHex("#ff4b00");
  Color get gray70011 => fromHex("#11555555");
  Color get blueGray200 => fromHex("#bac1ce");
  Color get gray400 => fromHex("#c4c4c4");
  Color get blueGray100 => fromHex("#d6dae2");
  Color get blueGray400 => fromHex("#74839d");
  Color get blue700 => fromHex("#FF079e4a");
  Color get blueGray300 => fromHex("#9ea8ba");
  Color get blueGray600 => fromHex("#5f6c86");
  Color get mainTheme => fromHex("#ff4da2a0");
  Color get gray80099 => fromHex("#993c3c43");
  Color get black9000c => fromHex("#0c000000");
  Color get gray300 => fromHex("#e3e4e5");
  Color get blue50 => fromHex("#e0ebff");
  Color get gray100 => fromHex("#f3f4f5");
  Color get black90075 => fromHex("#75000000");
  Color get black90033 => fromHex("#33000000");
  Color get blueGray40001 => fromHex("#888888");
  Color get whiteA700 => fromHex("#ffffff");
}

PrimaryTheme get appTheme => ThemeHelper().theme();
Color fromHex(String hexString) {
  final buffer = StringBuffer();
  if (hexString.length == 6 || hexString.length == 7) buffer.write('ff');
  buffer.write(hexString.replaceFirst('#', ''));
  return Color(int.parse(buffer.toString(), radix: 16));
}
